version: "3.7"

services:
  server:
    image: "nginx:1.18"
    container_name: "voice-neko-report-server"
    environment:
      VIRTUAL_HOST: "voice.neko.report"
      LETSENCRYPT_HOST: "voice.neko.report"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/certs:/etc/nginx/certs"
      - "./app:/usr/share/nginx/html"
    networks:
      voice-neko-report-network:
        aliases:
          - "server"
      nginx-network:

  php-fpm:
    image: "php-fpm:voice-neko-report"
    build:
      context: "./"
      dockerfile: "Dockerfile.php-fpm"
    container_name: "voice-neko-report-php-fpm"
    volumes:
      - "./app:/var/www/html"
    networks:
      voice-neko-report-network:
        aliases:
          - "php-fpm"
      mysql-network:

networks:
  voice-neko-report-network:
    name: "voice-neko-report-network"
    ipam:
      config:
        - subnet: "172.41.0.0/24"
  nginx-network:
    external: true
  mysql-network:
    external: true

